### ISSUE TITLE
requirements.txt 中包版本的问题

### ISSUE THREAD

**Issue by zyy2477** [Python3WebSpider/AccountPool#3]
在requirements.txt 中使用的Flask版本是0.12.1，代码运行的时候会报`ImportError: cannot import name 'Markup' from 'jinja2'`错误，
```python
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from accountpool.scheduler import Scheduler
  File "/data/web-spider2/chapter10/10.4/AccountPool/accountpool/scheduler.py", line 3, in <module>
    from accountpool.processors.server import app
  File "/data/web-spider2/chapter10/10.4/AccountPool/accountpool/processors/server.py", line 2, in <module>
    from flask import Flask, g
  File "/root/.virtualenvs/accountpool/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/root/.virtualenvs/accountpool/lib/python3.8/site-packages/jinja2/__init__.py)
```
和缺少 MarkupSafe ，报以下错误：
```python
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from accountpool.scheduler import Scheduler
  File "/data/web-spider2/chapter10/10.4/AccountPool/accountpool/scheduler.py", line 3, in <module>
    from accountpool.processors.server import app
  File "/data/web-spider2/chapter10/10.4/AccountPool/accountpool/processors/server.py", line 2, in <module>
    from flask import Flask, g
  File "/root/.virtualenvs/accountpool/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/root/.virtualenvs/accountpool/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/root/.virtualenvs/accountpool/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/root/.virtualenvs/accountpool/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/root/.virtualenvs/accountpool/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/.virtualenvs/accountpool/lib/python3.8/site-packages/markupsafe/__init__.py)
```
需要把改成 `Flask==0.12.1`改成`Flask==1.1.4`，和添加`MarkupSafe==2.0.1`。

**Comment by Germey** [comment]
谢谢，已经修改～
